### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by SeussCZ** [dpmcmlxxvi/olexp#41]
Is possible to implement geolocation to "OpenLayers Explorer"?

**Comment by dpmcmlxxvi** [comment]
OpenLayers Explorer combines a map with several convenient layout controls like a toolbar. You can use it to add any functionality you want to the toolbar. The [documentation](http://dpmcmlxxvi.github.io/olexp/docs/web/start.html) describes how the API returns an instance of a [w2ui toolbar](http://dpmcmlxxvi.github.io/olexp/docs/api/olexp.html#.ExplorerAPI). The toolbar can be used to add a button that provides a Geolocation functionality.

However, implementing a geolocation capability directly into olexp it out of scope. It is meant to be a platform to add any functionality you want.

If you create an example with geolocation capabilities feel free to add an issue pointing to it and I may add it to the examples page.
