### ISSUE TITLE
Set layer visibility

### ISSUE THREAD

**Issue by naub1n** [dpmcmlxxvi/olexp#44]
hi,

How i can set default visibility of layer when web application loading map ?
Exemple : 
```
// ==================================================
// Add heatmap
// --------------------------------------------------
var heatMap = new ol.layer.Heatmap({
      source: new ol.source.Vector({
          url: examples + '/data/kml/2012_Earthquakes_Mag5.kml',
          format: new ol.format.KML({extractStyles: false})
      }),
      blur: 10,
      radius: 10
});
heatMap.set('name','Heat Map');
```

When I add `heatMap.setVisible(false);`, layer is not visible but item in layers list is still activated.

**Comment by dpmcmlxxvi** [comment]
@naub1n Looks like you cannot at the moment. The initial visibility is not being checked before the layer is added to the explorer. It assumes the layer is visible, which is not correct. I'll try to push a patch soon.
